2025-02-25 16:13:26,848 - model_evaluation - ERROR - Failed to complete model evaluation: 'ActiveRun' object has no attribute 'info_id'
2025-02-26 18:57:03,565 - model_evaluation - ERROR - Failed to complete model evaluation: isinstance() arg 2 must be a type, a tuple of types, or a union
2025-03-03 15:32:37,041 - model_evaluation - ERROR - Failed to complete model evaluation: isinstance() arg 2 must be a type, a tuple of types, or a union
2025-03-20 16:13:50,738 - model_evaluation - ERROR - Failed to complete model evaluation: Failed to upload C:\Users\shahb\AppData\Local\Temp\tmpit37o11g\model\conda.yaml to yt-chrome-plugin/320616631867541258/ac7779f117dc49119d2742e1dcc99e6b/artifacts/lgbm_model/conda.yaml: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
2025-03-20 16:16:13,530 - model_evaluation - ERROR - Failed to complete model evaluation: Failed to upload C:\Users\shahb\AppData\Local\Temp\tmpj38hmlt7\model\conda.yaml to yt-chrome-plugin/320616631867541258/d802ee1508ef4911b44d7882fdd598ac/artifacts/lgbm_model/conda.yaml: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
2025-03-20 16:23:22,267 - model_evaluation - ERROR - Failed to complete model evaluation: Failed to upload C:\Users\shahb\AppData\Local\Temp\tmpd00crt1j\model\conda.yaml to yt-chrome-plugin/320616631867541258/fcbc4b12d04f48fe842b64e21672e818/artifacts/lgbm_model/conda.yaml: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
